/**
 * Generates TOOLS.md from the tool definitions in src/tools (single source of truth).
 * Run with: npm run docs:tools
 */

import { writeFileSync } from 'node:fs';
import { z } from 'zod';
import { ALL_TOOLS } from '../src/index.js';
import type { ToolDefinition } from '../src/tools/shared.js';

type AnyZod = z.ZodTypeAny;

/** Unwrap optional/default/effects wrappers to describe the underlying type. */
function describeType(schema: AnyZod): { type: string; required: boolean; defaultValue?: unknown } {
  let required = true;
  let defaultValue: unknown;
  let current: AnyZod = schema;

  for (;;) {
    if (current instanceof z.ZodOptional) {
      required = false;
      current = current.unwrap();
    } else if (current instanceof z.ZodDefault) {
      required = false;
      defaultValue = current._def.defaultValue();
      current = current._def.innerType;
    } else if (current instanceof z.ZodEffects) {
      current = current.innerType();
    } else {
      break;
    }
  }

  let type: string;
  if (current instanceof z.ZodString) type = 'string';
  else if (current instanceof z.ZodNumber) type = current.isInt ? 'integer' : 'number';
  else if (current instanceof z.ZodBoolean) type = 'boolean';
  else if (current instanceof z.ZodEnum) type = (current.options as string[]).map(o => `\`${o}\``).join(' \\| ');
  else if (current instanceof z.ZodArray) {
    const inner = current.element;
    type = inner instanceof z.ZodObject ? 'object[]' : `${describeType(inner).type}[]`;
  } else if (current instanceof z.ZodObject) type = 'object';
  else type = 'unknown';

  return { type, required, defaultValue };
}

function description(schema: AnyZod): string {
  // .describe() may sit on the wrapper or on the inner schema.
  let current: AnyZod | undefined = schema;
  while (current) {
    if (current.description) return current.description;
    current =
      current instanceof z.ZodOptional ? current.unwrap()
      : current instanceof z.ZodDefault ? current._def.innerType
      : current instanceof z.ZodEffects ? current.innerType()
      : undefined;
  }
  return '';
}

function paramTable(shape: z.ZodRawShape, localOnly: boolean): string[] {
  return Object.entries(shape).map(([name, schema]) => {
    const info = describeType(schema as AnyZod);
    const def = info.defaultValue !== undefined ? ` Default: \`${JSON.stringify(info.defaultValue)}\`.` : '';
    const local = localOnly ? ' **(local CLI only)**' : '';
    const base = description(schema as AnyZod);
    const stop = base && (def || local) && !/[.!?]$/.test(base) ? '.' : '';
    const text = `${base}${stop}${def}${local}`.replace(/\|/g, '\\|');
    return `| \`${name}\` | ${info.type} | ${info.required ? 'Yes' : 'No'} | ${text} |`;
  });
}

function annotationSummary(tool: ToolDefinition): string {
  const a = tool.annotations;
  if (a.destructiveHint) return 'Destructive (deletes data)';
  if (a.readOnlyHint) return 'Read-only';
  return 'Writes / spends credits (clients should ask first)';
}

const groups = [...new Set(ALL_TOOLS.map(t => t.group))];
const lines: string[] = [
  '# ZeroBounce MCP Server: tools',
  '',
  '<!-- Generated by scripts/generate-tools-md.ts from src/tools. Do not edit by hand; run `npm run docs:tools`. -->',
  '',
  `${ALL_TOOLS.length} tools, all prefixed \`zerobounce_\`. Every tool description includes its credit cost, and every tool carries MCP annotations (read-only / destructive) so clients can decide when to ask before running it.`,
  '',
  'Tools that return data accept `response_format`: `markdown` (default, readable summary) or `json` (raw ZeroBounce response).',
  '',
  '## Contents',
  '',
  ...groups.flatMap(group => [
    `- **${group}**: ${ALL_TOOLS.filter(t => t.group === group).map(t => `[\`${t.name}\`](#${t.name})`).join(', ')}`,
  ]),
  '',
];

for (const group of groups) {
  lines.push('---', '', `## ${group}`, '');
  for (const tool of ALL_TOOLS.filter(t => t.group === group)) {
    lines.push(`### \`${tool.name}\``, '', `**${tool.title}**`, '', tool.description, '');
    lines.push(`- **Cost:** ${tool.cost}`, `- **Behaviour:** ${annotationSummary(tool)}`, '');
    const rows = [...paramTable(tool.inputSchema, false), ...(tool.localInputSchema ? paramTable(tool.localInputSchema, true) : [])];
    if (rows.length) {
      lines.push('| Parameter | Type | Required | Description |', '|---|---|---|---|', ...rows, '');
    } else {
      lines.push('_No parameters._', '');
    }
  }
}

writeFileSync('TOOLS.md', lines.join('\n'));
console.log(`Wrote TOOLS.md (${ALL_TOOLS.length} tools)`);
